"""Extract real secret values from .secrets/prod-compose/* into a single
.secrets/vault.env file (KEY=VALUE, no quoting unless original had them).

This script is the inverse of sanitize_compose_templates.py — it captures concrete
values rather than masking them. The result is a private file kept under
.secrets/ (gitignored) and used by render_compose.py for drift-check.

Run from repo root:
  python ops/extract_vault.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / ".secrets" / "prod-compose"
OUT = ROOT / ".secrets" / "vault.env"

# (regex over a line, key-name-template)  — first capture group becomes the value.
# For per-host fields (SECRET_KEY), we encode host in the file we read from.
RULES = {
    # global keys (same value across all files where present)
    "JWT_AUTH_SECRET":         re.compile(r'JWT_AUTH_SECRET=([a-f0-9]{32,})'),
    "JWT_API_TOKENS_SECRET":   re.compile(r'JWT_API_TOKENS_SECRET=([a-f0-9]{32,})'),
    "POSTGRES_PASSWORD":       re.compile(r'^POSTGRES_PASSWORD=([^\s"${]+[^\s]*)$', re.MULTILINE),
    "POSTGRES_USER":           re.compile(r'^POSTGRES_USER=([^\s"${]+[^\s]*)$', re.MULTILINE),
    "POSTGRES_DB":             re.compile(r'^POSTGRES_DB=([^\s"${]+[^\s]*)$', re.MULTILINE),
    "METRICS_PASS":            re.compile(r'METRICS_PASS=([a-f0-9A-F]{16,})'),
    "WEBHOOK_SECRET_HEADER":   re.compile(r'WEBHOOK_SECRET_HEADER=([^\s"]+)'),
    "CLOUDFLARE_TOKEN":        re.compile(r'CLOUDFLARE_TOKEN=([^\s"]+)'),
    # REMNA machine JWTs: do not merge into one vault key — AMS shop/sub token ≠ LV
    # balancer/ru-monitor token (see docs/SECRETS.md §1).
    "BOT_TOKEN":               re.compile(r'(?:TELEGRAM_BOT_TOKEN|BOT_TOKEN)=("?[0-9]{6,}:[A-Za-z0-9_\-]+"?)'),
}

# host-specific node SECRET_KEY: file -> placeholder name
PER_HOST = {
    "lv/remnanode.env":          "SECRET_KEY_NODE_LV",
    "ams/remnanode-compose.yml": "SECRET_KEY_NODE_AMS",
    "nl/remnanode.env":          "SECRET_KEY_NODE_NL",
}

# Per-file Remnawave API JWT (shop/sub on AMS vs LV infra). Do not merge.
REMNA_FILE_KEYS: list[tuple[str, str, re.Pattern[str]]] = [
    ("ams/remna-shop.env", "REMNA_API_TOKEN_AMS",
     re.compile(r'^REMNA_API_TOKEN=("?eyJ[A-Za-z0-9._\-]+"?)', re.MULTILINE)),
    ("lv/etc-bvpn-balancer.env", "REMNA_API_TOKEN_LV",
     re.compile(r'^REMNA_API_TOKEN=("?eyJ[A-Za-z0-9._\-]+"?)', re.MULTILINE)),
]
SECRET_KEY_RE = re.compile(r'SECRET_KEY=("?eyJ[A-Za-z0-9+/=_\-]+"?)')

# bare-token style file: NL /etc/bvpn/bot-token (single-line)
BARE_BOT_TOKEN_FILE = "nl/etc-bvpn-bot-token.env"


def strip_quotes(v: str) -> str:
    v = v.strip()
    if (v.startswith('"') and v.endswith('"')) or \
       (v.startswith("'") and v.endswith("'")):
        v = v[1:-1]
    return v


def main() -> None:
    vault: dict[str, str] = {}
    collisions: list[tuple[str, str, str, str]] = []

    for src in sorted(SRC.glob("*/*.env")) + sorted(SRC.glob("*/*.yml")):
        rel = f"{src.parent.name}/{src.name}"
        text = src.read_text(encoding="utf-8")

        # bare-token NL bot-token file
        if rel == BARE_BOT_TOKEN_FILE:
            line = text.strip()
            if re.fullmatch(r'[0-9]{6,}:[A-Za-z0-9_\-]{20,}', line):
                v = line
                if "BOT_TOKEN" in vault and vault["BOT_TOKEN"] != v:
                    collisions.append(("BOT_TOKEN", vault["BOT_TOKEN"], v, rel))
                vault["BOT_TOKEN"] = v
            continue

        # per-host SECRET_KEY
        if rel in PER_HOST:
            m = SECRET_KEY_RE.search(text)
            if m:
                k = PER_HOST[rel]
                v = strip_quotes(m.group(1))
                vault[k] = v

        # generic keys
        for k, pat in RULES.items():
            for m in pat.finditer(text):
                v = strip_quotes(m.group(1))
                if k in vault and vault[k] != v:
                    collisions.append((k, vault[k], v, rel))
                else:
                    vault[k] = v

    for rel_path, vkey, pat in REMNA_FILE_KEYS:
        fp = SRC / rel_path
        if not fp.exists():
            continue
        text = fp.read_text(encoding="utf-8")
        m = pat.search(text)
        if m:
            vault[vkey] = strip_quotes(m.group(1))

    # Sort: per-host keys grouped, then alphabetical
    keys = sorted(vault.keys())
    lines = [
        "# BenderVPN vault.env — REAL secrets, gitignored, mode 0600 root:root.",
        "# Generated by ops/extract_vault.py from .secrets/prod-compose/.",
        "# DO NOT COMMIT THIS FILE.",
        "",
    ]
    for k in keys:
        lines.append(f"{k}={vault[k]}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {len(vault)} key(s) to {OUT.relative_to(ROOT)}")
    for k in keys:
        v = vault[k]
        preview = v if len(v) < 24 else v[:16] + "…(" + str(len(v)) + ")"
        print(f"  {k}={preview}")

    if collisions:
        print(f"\n!!! {len(collisions)} value collision(s) (same key, different values):")
        for k, a, b, where in collisions:
            print(f"  {k}: {a[:16]}…  vs  {b[:16]}…  (in {where})")
        print("\nReview manually — sanitize rules may need a host-specific split.")


if __name__ == "__main__":
    main()
